"use client";
import { motion } from "framer-motion";

const section = (delay = 0) => ({
  initial: { opacity: 0, y: 20 },
  whileInView: { opacity: 1, y: 0 },
  viewport: { once: true },
  transition: { duration: 0.5, delay },
});

export default function PrivacyPolicyPage() {
  return (
    <div className="bg-black min-h-screen">
      <div className="max-w-4xl mx-auto px-4 sm:px-6 lg:px-8 pt-28 sm:pt-32 pb-24">

        {/* Header */}
        <motion.div {...section()} className="mb-12">
          <span className="text-xs font-semibold tracking-widest text-primary uppercase">
            Legal
          </span>
          <h1 className="text-4xl sm:text-5xl font-bold text-white mt-3 mb-3">
            Privacy Policy
          </h1>
          <p className="text-zinc-500 text-sm">Last updated: August 16, 2024</p>
        </motion.div>

        <div className="space-y-12 text-zinc-400 leading-relaxed">

          {/* Intro */}
          <motion.section {...section(0.1)}>
            <p>
              This Privacy Policy describes Our policies and procedures on the collection, use, and
              disclosure of Your information when You use any of Our Services, including the Concira
              Home app, Concira Maintenance app, Concira website, and Concira dashboard. This
              document also informs You about Your privacy rights and how the law protects You.
            </p>
            <p className="mt-4">
              We use Your Personal data to provide and improve the Services. By using any of Our
              Services, You agree to the collection and use of information in accordance with this
              Privacy Policy.
            </p>
          </motion.section>

          {/* Interpretation and Definitions */}
          <motion.section {...section(0.1)}>
            <h2 className="text-2xl font-bold text-white mb-4">Interpretation and Definitions</h2>

            <h3 className="text-lg font-semibold text-white mb-2">Interpretation</h3>
            <p>
              The words of which the initial letter is capitalized have meanings defined under the
              following conditions. The following definitions shall have the same meaning regardless
              of whether they appear in singular or in plural.
            </p>

            <h3 className="text-lg font-semibold text-white mt-6 mb-3">Definitions</h3>
            <p className="mb-4">For the purposes of this Privacy Policy:</p>
            <ul className="space-y-3">
              {[
                ["Account", "means a unique account created for You to access our Services or parts of our Services."],
                ["Affiliate", 'means an entity that controls, is controlled by, or is under common control with a party, where "control" means ownership of 50% or more of the shares, equity interest, or other securities entitled to vote for election of directors or other managing authority.'],
                ["Application", "refers to any of the following software programs provided by the Company: Concira Home app, Concira Maintenance app."],
                ["Company", '(referred to as either "the Company", "We", "Us" or "Our" in this Agreement) refers to Concira.'],
                ["Cookies", "are small files that are placed on Your computer, mobile device, or any other device by a website, containing the details of Your browsing history on that website among its many uses."],
                ["Country", "refers to: Maharashtra, India"],
                ["Device", "means any device that can access the Service such as a computer, a cellphone, or a digital tablet."],
                ["Personal Data", "is any information that relates to an identified or identifiable individual."],
                ["Service", "refers to the Application, the Website, the Concira dashboard, or any combination thereof."],
                ["Service Provider", "means any natural or legal person who processes the data on behalf of the Company. It refers to third-party companies or individuals employed by the Company to facilitate the Service, to provide the Service on behalf of the Company, to perform services related to the Service, or to assist the Company in analyzing how the Service is used."],
                ["Usage Data", "refers to data collected automatically, either generated by the use of the Service or from the Service infrastructure itself (for example, the duration of a page visit)."],
                ["Website", "refers to Concira, accessible from https://www.concira.com."],
                ["You", "means the individual accessing or using the Service, or the company, or other legal entity on behalf of which such individual is accessing or using the Service, as applicable."],
              ].map(([term, def]) => (
                <li key={term} className="pl-4 border-l border-zinc-800">
                  <span className="font-semibold text-white">{term}</span>{" "}
                  {def}
                </li>
              ))}
            </ul>
          </motion.section>

          {/* Collecting and Using */}
          <motion.section {...section(0.1)}>
            <h2 className="text-2xl font-bold text-white mb-4">Collecting and Using Your Personal Data</h2>

            <h3 className="text-lg font-semibold text-white mb-2">Types of Data Collected</h3>

            <h4 className="font-semibold text-white mt-4 mb-2">Personal Data</h4>
            <p>
              While using Our Services, We may ask You to provide Us with certain personally
              identifiable information that can be used to contact or identify You. Personally
              identifiable information may include, but is not limited to:
            </p>
            <ul className="list-disc pl-6 mt-3 space-y-1">
              <li>Email address</li>
              <li>First name and last name</li>
              <li>Phone number</li>
              <li>Usage Data</li>
            </ul>

            <h4 className="font-semibold text-white mt-6 mb-2">Usage Data</h4>
            <p>
              Usage Data is collected automatically when using the Service. Usage Data may include
              information such as Your Device's Internet Protocol address (e.g., IP address),
              browser type, browser version, the pages of our Service that You visit, the time and
              date of Your visit, the time spent on those pages, unique device identifiers, and
              other diagnostic data.
            </p>
            <p className="mt-4">
              When You access the Service by or through a mobile device, We may collect certain
              information automatically, including, but not limited to, the type of mobile device
              You use, Your mobile device unique ID, the IP address of Your mobile device, Your
              mobile operating system, the type of mobile Internet browser You use, unique device
              identifiers, and other diagnostic data.
            </p>
            <p className="mt-4">
              We may also collect information that Your browser sends whenever You visit our Service
              or when You access the Service by or through a mobile device.
            </p>

            <h4 className="font-semibold text-white mt-6 mb-2">Information Collected while Using the Application</h4>
            <p>
              While using Our Applications, in order to provide features of Our Applications, We
              may collect, with Your prior permission:
            </p>
            <ul className="list-disc pl-6 mt-3 space-y-1">
              <li>Information regarding your location</li>
              <li>Pictures and other information from your Device's camera and photo library</li>
            </ul>
            <p className="mt-4">
              We use this information to provide features of Our Services, to improve and customize
              Our Services. The information may be uploaded to the Company's servers and/or a
              Service Provider's server or it may be simply stored on Your device.
            </p>
            <p className="mt-4">
              You can enable or disable access to this information at any time through Your Device
              settings.
            </p>

            <h4 className="font-semibold text-white mt-6 mb-2">Tracking Technologies and Cookies</h4>
            <p>
              We use Cookies and similar tracking technologies to track the activity on Our Services
              and store certain information. Tracking technologies used are beacons, tags, and
              scripts to collect and track information and to improve and analyze Our Services. The
              technologies We use may include:
            </p>
            <ul className="mt-3 space-y-3">
              <li className="pl-4 border-l border-zinc-800">
                <span className="font-semibold text-white">Cookies or Browser Cookies:</span> A
                cookie is a small file placed on Your Device. You can instruct Your browser to
                refuse all Cookies or to indicate when a Cookie is being sent. However, if You do
                not accept Cookies, You may not be able to use some parts of our Service. Unless
                You have adjusted Your browser setting so that it will refuse Cookies, our Services
                may use Cookies.
              </li>
              <li className="pl-4 border-l border-zinc-800">
                <span className="font-semibold text-white">Web Beacons:</span> Certain sections of
                our Services and our emails may contain small electronic files known as web beacons
                (also referred to as clear gifs, pixel tags, and single-pixel gifs) that permit the
                Company, for example, to count users who have visited those pages or opened an
                email and for other related website statistics.
              </li>
            </ul>
            <p className="mt-4">
              Cookies can be "Persistent" or "Session" Cookies. Persistent Cookies remain on Your
              personal computer or mobile device when You go offline, while Session Cookies are
              deleted as soon as You close Your web browser.
            </p>
            <p className="mt-4">
              We use both Session and Persistent Cookies for the purposes set out below:
            </p>
            <ul className="mt-3 space-y-4">
              {[
                {
                  name: "Necessary / Essential Cookies",
                  type: "Session Cookies",
                  admin: "Us",
                  purpose: "These Cookies are essential to provide You with services available through the Website and to enable You to use some of its features. They help to authenticate users and prevent fraudulent use of user accounts. Without these Cookies, the services that You have asked for cannot be provided, and We only use these Cookies to provide You with those services.",
                },
                {
                  name: "Cookies Policy / Notice Acceptance Cookies",
                  type: "Persistent Cookies",
                  admin: "Us",
                  purpose: "These Cookies identify if users have accepted the use of cookies on the Website.",
                },
                {
                  name: "Functionality Cookies",
                  type: "Persistent Cookies",
                  admin: "Us",
                  purpose: "These Cookies allow us to remember choices You make when You use the Website, such as remembering your login details or language preference. The purpose of these Cookies is to provide You with a more personal experience and to avoid You having to re-enter your preferences every time You use the Website.",
                },
              ].map((cookie) => (
                <li key={cookie.name} className="rounded-xl bg-zinc-900 border border-zinc-800 p-4">
                  <p className="font-semibold text-white mb-2">{cookie.name}</p>
                  <p><span className="text-zinc-500">Type:</span> {cookie.type}</p>
                  <p><span className="text-zinc-500">Administered by:</span> {cookie.admin}</p>
                  <p className="mt-1"><span className="text-zinc-500">Purpose:</span> {cookie.purpose}</p>
                </li>
              ))}
            </ul>
          </motion.section>

          {/* Use of Personal Data */}
          <motion.section {...section(0.1)}>
            <h2 className="text-2xl font-bold text-white mb-4">Use of Your Personal Data</h2>
            <p className="mb-3">The Company may use Personal Data for the following purposes:</p>
            <ul className="space-y-2">
              {[
                ["To provide and maintain our Services", "including to monitor the usage of our Services."],
                ["To manage Your Account", "to manage Your registration as a user of the Service. The Personal Data You provide can give You access to different functionalities of the Service that are available to You as a registered user."],
                ["For the performance of a contract", "the development, compliance, and undertaking of the purchase contract for the products, items, or services You have purchased or of any other contract with Us through the Service."],
                ["To contact You", "To contact You by email, telephone calls, SMS, or other equivalent forms of electronic communication, such as a mobile application's push notifications regarding updates or informative communications related to the functionalities, products, or contracted services, including security updates, when necessary or reasonable for their implementation."],
                ["To provide You with news, special offers, and general information", "about other goods, services, and events which we offer that are similar to those that you have already purchased or enquired about unless You have opted not to receive such information."],
                ["To manage Your requests", "To attend to and manage Your requests to Us."],
                ["For business transfers", "We may use Your information to evaluate or conduct a merger, divestiture, restructuring, reorganization, dissolution, or other sale or transfer of some or all of Our assets, whether as a going concern or as part of bankruptcy, liquidation, or similar proceeding, in which Personal Data held by Us about our Service users is among the assets transferred."],
                ["For other purposes", "We may use Your information for other purposes, such as data analysis, identifying usage trends, determining the effectiveness of our promotional campaigns, and to evaluate and improve our Services, products, services, marketing, and Your experience."],
              ].map(([title, desc]) => (
                <li key={title} className="pl-4 border-l border-zinc-800">
                  <span className="font-semibold text-white">{title}:</span> {desc}
                </li>
              ))}
            </ul>

            <p className="mt-6 mb-3">We may share Your personal information in the following situations:</p>
            <ul className="space-y-2">
              {[
                ["With Service Providers", "We may share Your personal information with Service Providers to monitor and analyze the use of our Services, to contact You."],
                ["For business transfers", "We may share or transfer Your personal information in connection with, or during negotiations of, any merger, sale of Company assets, financing, or acquisition of all or a portion of Our business to another company."],
                ["With Affiliates", "We may share Your information with Our affiliates, in which case we will require those affiliates to honor this Privacy Policy. Affiliates include Our parent company and any other subsidiaries, joint venture partners, or other companies that We control or that are under common control with Us."],
                ["With business partners", "We may share Your information with Our business partners to offer You certain products, services, or promotions."],
                ["With other users", "when You share personal information or otherwise interact in the public areas with other users, such information may be viewed by all users and may be publicly distributed outside."],
                ["With Your consent", "We may disclose Your personal information for any other purpose with Your consent."],
              ].map(([title, desc]) => (
                <li key={title} className="pl-4 border-l border-zinc-800">
                  <span className="font-semibold text-white">{title}:</span> {desc}
                </li>
              ))}
            </ul>
          </motion.section>

          {/* Retention */}
          <motion.section {...section(0.1)}>
            <h2 className="text-2xl font-bold text-white mb-4">Retention of Your Personal Data</h2>
            <p>
              The Company will retain Your Personal Data only for as long as is necessary for the
              purposes set out in this Privacy Policy. We will retain and use Your Personal Data to
              the extent necessary to comply with our legal obligations (for example, if we are
              required to retain your data to comply with applicable laws), resolve disputes, and
              enforce our legal agreements and policies.
            </p>
            <p className="mt-4">
              The Company will also retain Usage Data for internal analysis purposes. Usage Data is
              generally retained for a shorter period of time, except when this data is used to
              strengthen the security or to improve the functionality of Our Services, or We are
              legally obligated to retain this data for longer time periods.
            </p>
          </motion.section>

          {/* Transfer */}
          <motion.section {...section(0.1)}>
            <h2 className="text-2xl font-bold text-white mb-4">Transfer of Your Personal Data</h2>
            <p>
              Your information, including Personal Data, is processed at the Company's operating
              offices and in any other places where the parties involved in the processing are
              located. It means that this information may be transferred to — and maintained on —
              computers located outside of Your state, province, country, or other governmental
              jurisdiction where the data protection laws may differ from those from Your
              jurisdiction.
            </p>
            <p className="mt-4">
              Your consent to this Privacy Policy followed by Your submission of such information
              represents Your agreement to that transfer.
            </p>
            <p className="mt-4">
              The Company will take all steps reasonably necessary to ensure that Your data is
              treated securely and in accordance with this Privacy Policy and no transfer of Your
              Personal Data will take place to an organization or a country unless there are
              adequate controls in place including the security of Your data and other personal
              information.
            </p>
          </motion.section>

          {/* GDPR */}
          <motion.section {...section(0.1)}>
            <h2 className="text-2xl font-bold text-white mb-4">
              Your Data Protection Rights Under the General Data Protection Regulation (GDPR)
            </h2>
            <p>
              If You are a resident of the European Economic Area (EEA), You have certain data
              protection rights. The Company aims to take reasonable steps to allow You to correct,
              amend, delete, or limit the use of Your Personal Data.
            </p>

            <h3 className="text-lg font-semibold text-white mt-6 mb-2">Delete Your Personal Data</h3>
            <p>
              You have the right to delete or request that We assist in deleting the Personal Data
              that We have collected about You.
            </p>
            <p className="mt-4">
              Our Service may give You the ability to delete certain information about You from
              within the Service.
            </p>
            <p className="mt-4">
              You may update, amend, or delete Your information at any time by signing in to Your
              Account, if you have one, and visiting the account settings section that allows you
              to manage Your personal information. You may also contact Us to request access to,
              correct, or delete any personal information that You have provided to Us.
            </p>
            <p className="mt-4">
              Please note, however, that We may need to retain certain information when we have a
              legal obligation or lawful basis to do so.
            </p>
          </motion.section>

          {/* Disclosure */}
          <motion.section {...section(0.1)}>
            <h2 className="text-2xl font-bold text-white mb-4">Disclosure of Your Personal Data</h2>

            <h3 className="text-lg font-semibold text-white mb-2">Business Transactions</h3>
            <p>
              If the Company is involved in a merger, acquisition or asset sale, Your Personal Data
              may be transferred. We will provide notice before Your Personal Data is transferred
              and becomes subject to a different Privacy Policy.
            </p>

            <h3 className="text-lg font-semibold text-white mt-6 mb-2">Law Enforcement</h3>
            <p>
              Under certain circumstances, the Company may be required to disclose Your Personal
              Data if required to do so by law or in response to valid requests by public
              authorities (e.g. a court or a government agency).
            </p>

            <h3 className="text-lg font-semibold text-white mt-6 mb-2">Other Legal Requirements</h3>
            <p className="mb-3">
              The Company may disclose Your Personal Data in the good faith belief that such action
              is necessary to:
            </p>
            <ul className="list-disc pl-6 space-y-1">
              <li>Comply with a legal obligation</li>
              <li>Protect and defend the rights or property of the Company</li>
              <li>Prevent or investigate possible wrongdoing in connection with the Service</li>
              <li>Protect the personal safety of Users of the Service or the public</li>
              <li>Protect against legal liability</li>
            </ul>
          </motion.section>

          {/* Security */}
          <motion.section {...section(0.1)}>
            <h2 className="text-2xl font-bold text-white mb-4">Security of Your Personal Data</h2>
            <p>
              The security of Your Personal Data is important to Us, but remember that no method of
              transmission over the Internet, or method of electronic storage is 100% secure. While
              We strive to use commercially acceptable means to protect Your Personal Data, We
              cannot guarantee its absolute security.
            </p>
          </motion.section>

          {/* Children's Privacy */}
          <motion.section {...section(0.1)}>
            <h2 className="text-2xl font-bold text-white mb-4">Children's Privacy</h2>
            <p>
              Our Service does not address anyone under the age of 13. We do not knowingly collect
              personally identifiable information from anyone under the age of 13. If You are a
              parent or guardian and You are aware that Your child has provided Us with Personal
              Data, please contact Us. If We become aware that We have collected Personal Data from
              anyone under the age of 13 without verification of parental consent, We take steps to
              remove that information from Our servers.
            </p>
            <p className="mt-4">
              If We need to rely on consent as a legal basis for processing Your information and
              Your country requires consent from a parent, We may require Your parent's consent
              before We collect and use that information.
            </p>
          </motion.section>

          {/* Links */}
          <motion.section {...section(0.1)}>
            <h2 className="text-2xl font-bold text-white mb-4">Links to Other Websites</h2>
            <p>
              Our Service may contain links to other websites that are not operated by Us. If You
              click on a third party link, You will be directed to that third party's site. We
              strongly advise You to review the Privacy Policy of every site You visit.
            </p>
            <p className="mt-4">
              We have no control over and assume no responsibility for the content, privacy policies
              or practices of any third party sites or services.
            </p>
          </motion.section>

          {/* Changes */}
          <motion.section {...section(0.1)}>
            <h2 className="text-2xl font-bold text-white mb-4">Changes to this Privacy Policy</h2>
            <p>
              We may update Our Privacy Policy from time to time. We will notify You of any changes
              by posting the new Privacy Policy on this page.
            </p>
            <p className="mt-4">
              We will let You know via email and/or a prominent notice on Our Service, prior to the
              change becoming effective and update the "Last updated" date at the top of this
              Privacy Policy.
            </p>
            <p className="mt-4">
              You are advised to review this Privacy Policy periodically for any changes. Changes
              to this Privacy Policy are effective when they are posted on this page.
            </p>
          </motion.section>

          {/* Contact */}
          <motion.section {...section(0.1)}>
            <h2 className="text-2xl font-bold text-white mb-4">Contact Us</h2>
            <p className="mb-4">
              If you have any questions about this Privacy Policy, You can contact us:
            </p>
            <div className="rounded-xl bg-zinc-900 border border-zinc-800 p-6 space-y-3">
              <p>
                <span className="text-zinc-500">By email:</span>{" "}
                <a
                  href="mailto:contactus@concira.com"
                  className="text-primary hover:text-primary/80 transition-colors"
                >
                  contactus@concira.com
                </a>
              </p>
              <p>
                <span className="text-zinc-500">By visiting this page on our website:</span>{" "}
                <a
                  href="https://www.concira.com"
                  target="_blank"
                  rel="noopener noreferrer"
                  className="text-primary hover:text-primary/80 transition-colors"
                >
                  www.concira.com
                </a>
              </p>
            </div>
          </motion.section>

        </div>
      </div>
    </div>
  );
}
